### ISSUE TITLE
Ftpd leaks sockets

### ISSUE THREAD

**Issue by rogierschouten** [sstur/nodeftpd#43]
Currently there is no way to close the server and be sure all sockets are closed. The close() method only closes the main listening socket but not the data sockets. Is there any way around that?

**Comment by rogierschouten** [comment]
Actually, it's the pasv server associated with each connection that is not closed.

**Comment by sstur** [comment]
Agreed, this is an issue that should be resolved. I'll accept a pull request for this, if not, I will try to get to it. Thanks.

**Comment by rogierschouten** [comment]
I'l' have to see about that - I'm under pressure to deliver something and I've worked around it by closing the pasv field of the connection object that was passed in the connected event. 

By the way I've added TypeScript definitions for your module on borisyankov/DefinitelyTyped so your  module can be used from TypeScript as well. You might see an increase in usage :)

**Comment by sstur** [comment]
Quoting from @rogierschouten's comment on #42 I think this is a good solution (although we should bake this in and expose a simpler way to do this).

*== Original Message ==*

1. Attach a handler to the "client:connected" event and store the connection object you get (called 'client' below).
2. When you want to dispose, do this:

```javascript
if (client.dataSocket) {
      client.dataSocket.destroy();
}
if (client.socket) {
      client.socket.destroy();
}
if (client.pasv) {
      client.pasv.close();
}
```

**Comment by BenasPaulikas** [comment]
@sstur @rogierschouten After implementing it. This is what I get after disconnecting from FTP:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: This socket is closed.
    at Socket._write (net.js:638:19)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Socket.Writable.write (_stream_writable.js:183:11)
    at Socket.write (net.js:616:40)
    at wwenc (/home/node/node_modules/ftpd/lib/ftpd.js:74:17)
    at FtpConnection.respond (/home/node/node_modules/ftpd/lib/ftpd.js:201:12)
    at FtpServer._onConnection (/home/node/node_modules/ftpd/lib/ftpd.js:153:8)
    at Server.<anonymous> (/home/node/node_modules/ftpd/lib/ftpd.js:108:10)
    at Server.emit (events.js:95:17)
    at TCP.onconnection (net.js:1192:8)

**Comment by mk-pmb** [comment]
What's the benefit of `.destroy()` over `.end()` in this case?

**Comment by BenasPaulikas** [comment]
Problem is: After ftp client disconnects, on command
   netstat -tulpn | grep node.js 

I see many unclosed, established connections.. After reaching ~1024 node app crashes..

**Comment by BenasPaulikas** [comment]
![node](https://cloud.githubusercontent.com/assets/6473565/12216509/32672dbc-b6ed-11e5-8156-71d21ba10cd3.png)
Each row is generated after 1 client disconnects from FTP. Later - everything in app is broken and needs restart because it reaches ulimit..

**Comment by rogierschouten** [comment]
@mk-pmb end() takes longer than destroy() as it will perform a Fin-Ack handshake I thought. I'm in unittests so I want a quick end without a lingering connection.

@BenasPaulikas  what is your code? Did you attach the event handler, store the connection object, and close the connections when you're done with them? It looks like you tried to write after you closed the connections.

**Comment by BenasPaulikas** [comment]
@rogierschouten Let me begin again because I made a mistake before. So I have a simple server enabled.

```javascript
var server = new ftpd.FtpServer('127.0.0.1', options);

server.on('client:connected', function(conn) {
   ...
   conn.on('command:pass', function(pass, success, failure) {
      ...
      success();
   })
})
```

I connect to edit, edit few files perfectly and disconnect. Each time I connect it's opening and not closing a socket connection(marked red in image) So when I connect ~ 1024th time(max ulimit) my node app starts crashing because other module can't no more open files because it reached ulimit..

![node1](https://cloud.githubusercontent.com/assets/6473565/12218190/eb1e4b32-b720-11e5-9cb5-a75686b2b8c2.png)

**Comment by sstur** [comment]
@mk-pmb The `destroy()` method "ensures that no more I/O activity happens on this socket. Only necessary in case of errors (parse error or so)."

So I think the `end()` method would be a better choice. Regardless, this seems to be a bug and we should get a fix out. I'll take a closer look at implementing @rogierschouten's solution...

**Comment by rogierschouten** [comment]
If you use end(), sockets will not leak but they will linger. For some uses this is not acceptable. Why not offer both while you're at it? Small effort big result.

**Comment by sstur** [comment]
@rogierschouten You mean like a `destroySockets` opt-in? I'm open to that, but it will add more complexity to test for (config permutations). I wonder if we do a setTimeout to check if a socket it still open after N milliseconds and destroy if necessary, would that solve your use case? How long are these lingering for?

**Comment by rogierschouten** [comment]
That's OS specific, node does not control that. It is tpically more than 30
seconds because the protocol takes three messages with their possible
timeouts and retries. Servers typically have separate end() and destroy()
methods. There are use cases for both. Depending on your implementation you
may want to treat destroy as one more unittest rather than permutating it
with other config options.

**Comment by sstur** [comment]
I see. Hmm, well something like this could solve your use case, right:

    server.on('connection', function(connection) {
      connection.on('end', function() {
        connection.destroy();
      });
    });

I'm actually not opposed to adding a config option, I just want to explore the options and make sure we make a good choice.

**Comment by rogierschouten** [comment]
Well no, because you would send the end event only when ending is finished, i,e, after the 30+ seconds?

**Comment by sstur** [comment]
Oops, you're right. What I was trying to say is imagine we had an event that fired when `socket.end()` is called and allowed your code to choose what it wants to do. I guess I should have looked at the API docs first. Turns out there is no built in event for this so we would have to fire a custom event and that could possibly be confusing. I'll go with the config option.

**Comment by mk-pmb** [comment]
Considering @BenasPaulikas' `"Error: This socket is closed." at wwenc (…/ftpd/lib/ftpd.js:74:17)`, we should add graceful error handling. [This StackOverflow thread](http://stackoverflow.com/questions/12735285/node-js-uncaught-socket-exception-socket-is-closed) looks like we'd need a try-catch in `wwnec`, as this seems to not emit an error event on the socket.

**Comment by BenasPaulikas** [comment]
@sstur Do I understand this correct. We need a config option which would allow FTP module to fully close these unused connections ?
![list](https://cloud.githubusercontent.com/assets/6473565/12223498/e8acbafc-b7e1-11e5-8d2c-62e1b7b643dc.png)

**Comment by sstur** [comment]
Thanks @mk-pmb. It seems in addition to calling `destroy()` instead of `end()` we can check `socket.writable` and possibly `socket.destroyed` before writing (or even look for the presence of `socket._handle` but underscore-prefixed properties are meant to be private). I have a diff for this almost ready.

**Comment by mk-pmb** [comment]
When deciding about whether to attempt writing to the socket, assuming a good API, no other socket property other than `socket.writable` should be of concern.

**Comment by BenasPaulikas** [comment]
I'm still confused. We don't have a solution yet to solve these open listen ports

**Comment by sstur** [comment]
I think I have a solution. Will push my changes tomorrow and maybe you can help me see if it solves the issue...

**Comment by BenasPaulikas** [comment]
I will be waiting to test. Can't wait :+1:

**Comment by oleksiyk** [comment]
Hi guys!

I also experienced leaking sockets a while ago and the first thing I tried was [this](https://github.com/oleksiyk/nodeftpd/commit/6ef70cc361cc9df55f67b674c77b9c80d5a3c1f7) and I never had any leaking sockets since. 

I'm not sure this was correct but I forgot to continue on this because the problem disappeared.

**Comment by sstur** [comment]
@BenasPaulikas: I have pushed my fix to master. Can you try it out and see if it fixes your issue? I need a way to test for lingering listeners, but that will take a little refactoring.
@oleksiyk: That's actually a very elegant solution! I think even more so than mine (although I hope to have a better one soon after I refactor the pasv listener to a module). One point though, you probably only need that in the `_onClose` since "close" event is guaranteed to be emitted after error/end. So actually, yours could even be a one-line solution!

**Comment by BenasPaulikas** [comment]
@sstur It works! Sockets are closed without any error :+1: . Is this is a final solution ? When can I expect this to work via npm install :) ?

**Comment by sstur** [comment]
I can bump the version and push to npm today. Thanks!

**Comment by dushyantbangal** [comment]
@sstur was this pushed to npm? Because I'm still settings the issue and I'm not able to see the solution `this._closeDataConnections();` implemented in the `ftpd.js`.

Also, I did do this on my own, only in `_onClose`, it works for some time, but then again all of my ports get consumed.
